### ISSUE TITLE
Infinite recursion in django 1.10 with model.refresh_from_db()

### ISSUE THREAD

**Issue by soby** [ocadotechnology/django-closuretree#32]
```
python manage.py test --keepdb myapp.widget
Using existing test database for alias 'default'...
^C^CTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 550, in run_tests
    result = self.run_suite(suite)
  File "/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 511, in run_suite
    ).run(suite)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/venv/local/lib/python2.7/site-packages/django/test/testcases.py", line 213, in __call__
    super(SimpleTestCase, self).__call__(result)
  File "/usr/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/app/myapp/widget/tests/api/v1/views/test_location.py", line 265, in test_active_filter
    TARG_OBJ = self.get_target_object()
  File "/app/myapp/core/tests/api/v1/views/base.py", line 520, in get_target_object
    return refetch(cls.obj)
  File "/app/myapp/core/tests/api/v1/views/base.py", line 186, in refetch
    obj.refresh_from_db()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 685, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 66, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 565, in from_db
    new = cls(*values)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 481, in __init__
    setattr(self, field.attname, val)
  File "/venv/local/lib/python2.7/site-packages/closuretree/models.py", line 100, in __setattr__
    hasattr(self, id_field_name) and  # It's already been set
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query_utils.py", line 115, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 685, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 66, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 565, in from_db
    new = cls(*values)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 481, in __init__
    setattr(self, field.attname, val)
  File "/venv/local/lib/python2.7/site-packages/closuretree/models.py", line 100, in __setattr__
    hasattr(self, id_field_name) and  # It's already been set
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query_utils.py", line 115, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 685, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 66, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 565, in from_db
    new = cls(*values)
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 481, in __init__
    setattr(self, field.attname, val)
  File "/venv/local/lib/python2.7/site-packages/closuretree/models.py", line 100, in __setattr__
    hasattr(self, id_field_name) and  # It's already been set
  File "/venv/local/lib/python2.7/site-packages/django/db/models/query_utils.py", line 115, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 685, in refresh_from_db
```

**Comment by mikebryant** [comment]
Sorry, I dropped the ball here. Looks like we don't support 1.10 properly, I'm looking into it
