### ISSUE TITLE
How rewrite rebuildtable function correctly?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [ocadotechnology/django-closuretree#46]
Hello! :) First of all **THANK YOU** for this wonderful project!

I tried to rewrite little bit [rebuildtable](https://github.com/ocadotechnology/django-closuretree/blob/d6e4255245366a61296fd72dbe74ae28fbcb93e6/closuretree/models.py#L134) function but unfortunately it don't work as I expected. Can you guys say where I make mistake?

I show tree in template with the help of [Nestable2](https://github.com/RamonSmit/Nestable2) plugin. This plugin allows user to change the order of tree nodes. When user click special button I send JSON by ajax. I need to save new structure of tree.

Be the way I have for example such JSON: `[{"id":1},{"id":2},{"id":3,"children":[{"id":4},{"id":5,"foo":"bar"}]}]` by `serialize` function of that plugin.

**views.py:**
```
class NodeOrderView(CsrfExemptMixin, JsonRequestResponseMixin, FormView):
    def post(self, request, *args, **kwargs):
        Node.tree_update(None, self.request_json)
        return self.render_json_response({'saved': 'ok'})
```

**models.py:**
```
    @classmethod
    def tree_update(cls, parent_id, children, position=0):
        parent_id=0
        for child in children:
            # In "parent_id" field of "Node" table store 0 instead of None
            if parent_id==None:
                parent_id=0

            # Update data in "Node" table
            cls.objects.filter(pk=child['id']).update(parent_id=parent_id, position=position)

            # Delete data from "Node Closure" table
            cls._closure_model.objects.filter(parent_id=child['id']).delete()

            # Create data in "Node Closure" table
            cls._closure_model.objects.bulk_create([cls._closure_model(
                parent_id=x['pk'],
                child_id=x['pk'],
                depth=0
            ) for x in cls.objects.filter(pk=child['id']).values("pk")])
            for node in cls.objects.filter(pk=child['id']):
                node._closure_createlink()

            # Position
            position = cls.tree_update(child['id'], child.get('children', []), position+1)
        return position
```
I have next error. Also this code in "Node Closure" table delete all entries besides root nodes (depth=0). 
**ERROR:**
```
Traceback (most recent call last):
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/braces/views/_forms.py", line 24, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/braces/views/_ajax.py", line 144, in dispatch
    request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Applications/Projects/web/custom project/tree/views.py", line 57, in post
    Node.tree_update(None, self.request_json)
  File "/Applications/Projects/web/custom project/tree/models.py", line 89, in tree_update
    position = cls.document_table_update(child['id'], child.get('children', []), position+1)
  File "/Applications/Projects/web/custom_project/tree/models.py", line 87, in tree_update
    node._closure_createlink()
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/closuretree/models.py", line 196, in _closure_createlink
    child__pk=self._closure_parent_pk
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/closuretree/models.py", line 182, in _closure_parent_pk
    return parent.pk if parent else None
AttributeError: 'int' object has no attribute 'pk'
```

Do you have any ideas whats wrong?

**Comment by NogerbekNurzhan** [comment]
I am notice next thing:
1. successfully update data in "Node" table.
2. successfully delete data from "Node Closure" table
3. problems happens in this [line](https://github.com/ocadotechnology/django-closuretree/blob/d6e4255245366a61296fd72dbe74ae28fbcb93e6/closuretree/models.py#L196). **Error**: `AttributeError: 'int' object has no attribute 'pk'`

**Comment by NogerbekNurzhan** [comment]
Finally I found my mistake. It was in parent_id field of main table.  I'm sorry to interrupt.

**THANK YOU** guys for this wonderful project!!! :)
